<a href="https://colab.research.google.com/github/faudhim5-buddy/belajar-ai-30-hari/blob/main/Day_20_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import re

def bersihkan_teks(teks):
  teks = teks.lower()
  teks = re.sub(r'[^\w\s]','', teks)
  return teks

def tokenisasi(teks):
  return teks.split()

stopwords = ["yang", "dan", "di", "ke", "dari", "untuk"
            "ini", "itu", "adalah", "dengan", "tidak", "saya"]

def hapus_stopwords(tokens):
  return [kata for kata in tokens if kata not in stopwords]

kalimat = "Saya tidak suka dengan pelayanan ini!"
bersih = bersihkan_teks(kalimat)
tokens = tokenisasi(bersih)
tokens_bersih = hapus_stopwords(tokens)

print("kalimat asli:", kalimat)
print("setelah dibersihkan:", bersih)
print("seletah di tokenisasi:", tokens)
print("setelah hapus stopwords:", tokens_bersih)

kalimat asli: Saya tidak suka dengan pelayanan ini!
setelah dibersihkan: saya tidak suka dengan pelayanan ini
seletah di tokenisasi: ['saya', 'tidak', 'suka', 'dengan', 'pelayanan', 'ini']
setelah hapus stopwords: ['suka', 'pelayanan', 'ini']


In [ ]:
from numpy import vectorize
from sklearn.feature_extraction.text import CountVectorizer


kalimat = [
    "film ini sangat bagus dan menarik",
    "pelayanan sangat buruk dan mengecewakan",
    "produk bagus tapi pengiriman lambat",
    "sangat puas dengan produk ini",
    "tidak puas sama sekali sangat buruk",
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(kalimat)


print("Kosakata yang ditemukan :")
print(vectorizer.get_feature_names_out())
print()
print("Matirks angka dari teks :")
print(X.toarray())
print()



Kosakata yang ditemukan :
['bagus' 'buruk' 'dan' 'dengan' 'film' 'ini' 'lambat' 'menarik'
 'mengecewakan' 'pelayanan' 'pengiriman' 'produk' 'puas' 'sama' 'sangat'
 'sekali' 'tapi' 'tidak']

Matirks angka dari teks :
[[1 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0]
 [0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1]]

Akurasi analisis sentimen : 100.0 %


In [ ]:
from numpy import vectorize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

ulasan = [
    "produk ini sangat bagus dan berkualitas",
    "saya sangat puas dengan pembelian ini",
    "pengiriman cepat produk sesuai deskripsi",
    "barang bagus harga terjangkau recommended",
    "kualitas sangat baik akan beli lagi",
    "produk ini mengecewakan dan sangat buruk",
    "kualitas jelek tidak sesuai gambar",
    "pengiriman lambat barang rusak kecewa",
    "tidak recommended sama sekali buang uang",
    "pelayanan buruk tidak sesuai deskripsi",
    "barang rusak saat diterima sangat kecewa",
    "produk mengecewakan tidak sesuai ekspektasi",
    "lumayan bagus tapi pengiriman agak lama",
    "cukup puas meski ada kekurangan kecil",
    "barang tiba cepat kualitas memuaskan",
]

label = ["postif", "postif", "postif", "postif", "postif",
         "negatif", "negatif","negatif", "negatif", "negatif",
         "negatif", "negatif",
         "positif", "positif", "positif",]

X_latih, X_uji, y_latih, y_uji = train_test_split(
    ulasan, label, test_size=0.2, random_state=42
)

vectorizer = CountVectorizer()
X_latih_vec = vectorizer.fit_transform(X_latih)
X_uji_vec = vectorizer.transform(X_uji)

model = MultinomialNB()
model.fit(X_latih_vec, y_latih)

y_pred = model.predict(X_uji_vec)
akurasi = accuracy_score(y_uji, y_pred)

print("Akurasi analisis sentimen :", akurasi*100, "%")
print()

ulasan_baru = [
    "produk sangat bagus dan memuaskan",
    "barang rusak dan buat kecewa",
    "lumayan bagus tapi pengiriman lambat",
    "lumayan bagus tapi agak lambat",
    "produk tidak berkualitas dan membuat sedih",
]

ulasan_baru_vec = vectorizer.transform(ulasan_baru)
prediksi = model.predict(ulasan_baru_vec)


for i, ulasan in enumerate(ulasan_baru):
  print(f'"{ulasan}"')
  print(f"adalah sentimen : {prediksi[i]}")
  print()
print(vectorizer.get_feature_names_out(ulasan_baru_vec))

Akurasi analisis sentimen : 100.0 %

"produk sangat bagus dan memuaskan"
adalah sentimen : postif

"barang rusak dan buat kecewa"
adalah sentimen : negatif

"lumayan bagus tapi pengiriman lambat"
adalah sentimen : positif

"lumayan bagus tapi agak lambat"
adalah sentimen : positif

"produk tidak berkualitas dan membuat sedih"
adalah sentimen : negatif

['ada' 'agak' 'akan' 'bagus' 'baik' 'barang' 'beli' 'buang' 'buruk'
 'cepat' 'cukup' 'dan' 'dengan' 'deskripsi' 'diterima' 'gambar' 'harga'
 'ini' 'jelek' 'kecewa' 'kecil' 'kekurangan' 'kualitas' 'lagi' 'lama'
 'lambat' 'lumayan' 'memuaskan' 'mengecewakan' 'meski' 'pembelian'
 'pengiriman' 'produk' 'puas' 'recommended' 'rusak' 'saat' 'sama' 'sangat'
 'saya' 'sekali' 'sesuai' 'tapi' 'terjangkau' 'tiba' 'tidak' 'uang']
