<a href="https://colab.research.google.com/github/faudhim5-buddy/belajar-ai-30-hari/blob/main/Day_8_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

angka = np.array([10,20,30,40,50,])

print(angka)
print(type(angka))
print(angka.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)


In [ ]:
import numpy as np

nilai = np.array([7,8,9,10,])

print(nilai*2)
print(nilai+9)
print(nilai.mean())
print(nilai.max())
print(nilai.min())

[14 16 18 20]
[16 17 18 19]
8.5
10
7


In [ ]:
import numpy as np

list_biasa = [10,15,20,25,30,35,40]
print(list_biasa * 2)

nilai_array = np.array([13,17,19,23,29,31])
print(nilai_array * 2)

[10, 15, 20, 25, 30, 35, 40, 10, 15, 20, 25, 30, 35, 40]
[26 34 38 46 58 62]


In [ ]:
import numpy as np

tabel = np.array ([
    [2,3,4],
    [5,6,7],
    [8,9,10]
])

print(tabel)
print(tabel.shape)
print(tabel[0])
print(tabel[0][1])

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
[2 3 4]
3
